name: PWD Test

on:
  workflow_dispatch:

jobs:
  check-directory:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - name: Show directory contents
        run: ls -la

      - name: Show current directory
        run: pwd

      - name: Change Directory and PWD
        run: |
          cd ../
          pwd

      - name: Show current directory
        run: pwd